package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
import ua.divas.view.common.CurrencyView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 07 21:36:35 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CurrencyViewImpl extends DivasView implements CurrencyView {
    /**
     * This is the default constructor (do not remove).
     */
    public CurrencyViewImpl() {
    }

    public void doCurrencyExchange() {
        callStoredProcedure("CURRENCY_PKG.GETRATEBYSHEDULE()", null);
        System.out.println("Called CURRENCY_PKG.GETRATEBYSHEDULE");

    }
}

