package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
import ua.divas.view.common.DivisionsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 16 18:08:07 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DivisionsViewImpl extends DivasView implements DivisionsView {
    /**
     * This is the default constructor (do not remove).
     */
    public DivisionsViewImpl() {
    }
    
    public String retrieveDivisionsFirstParentId() {
        return (String)callStoredFunction(VARCHAR2,"UTILITY.retrieve_division_parentid", new Object[] {});
    }
    
    public void changeParentInDivisions(String Id, String ParentId) {
        //AppModuleImpl am = (AppModuleImpl)BindingContext.getCurrent().getDefaultDataControl().getApplicationModule();
        callStoredProcedure("UTILITY.change_parent_in_division(?,?)", new Object[] {Id,ParentId});
        //am.getTransaction().commit();
    }

    /**
     * Returns the bind variable value for u_name.
     * @return bind variable value for u_name
     */
    public String getu_name() {
        return (String) getNamedWhereClauseParam("u_name");
    }

    /**
     * Sets <code>value</code> for bind variable u_name.
     * @param value value to bind as u_name
     */
    public void setu_name(String value) {
        setNamedWhereClauseParam("u_name", value);
    }
}

