package ua.divas.view;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 15 19:15:50 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FirmsViewImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public FirmsViewImpl() {
    }
    
    /* @Override
    public void insertRow(Row row) {
       super.insertRow(row);
       row.removeAndRetain();
       last();
       next();
       getDefaultRowSet().insertRow(row);
    } */
}

