package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 04 16:25:59 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KassaViewImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public KassaViewImpl() {
    }

    /**
     * Returns the variable value for CId.
     * @return variable value for CId
     */
    public String getCId() {
        return (String) ensureVariableManager().getVariableValue("CId");
    }

    /**
     * Sets <code>value</code> for variable CId.
     * @param value value to bind as CId
     */
    public void setCId(String value) {
        ensureVariableManager().setVariableValue("CId", value);
    }

    /**
     * Returns the variable value for DId.
     * @return variable value for DId
     */
    public String getDId() {
        return (String) ensureVariableManager().getVariableValue("DId");
    }

    /**
     * Sets <code>value</code> for variable DId.
     * @param value value to bind as DId
     */
    public void setDId(String value) {
        ensureVariableManager().setVariableValue("DId", value);
    }

    /**
     * Returns the variable value for KassaName.
     * @return variable value for KassaName
     */
    public String getKassaName() {
        return (String) ensureVariableManager().getVariableValue("KassaName");
    }

    /**
     * Sets <code>value</code> for variable KassaName.
     * @param value value to bind as KassaName
     */
    public void setKassaName(String value) {
        ensureVariableManager().setVariableValue("KassaName", value);
    }

    /**
     * Returns the bind variable value for u_name.
     * @return bind variable value for u_name
     */
    public String getu_name() {
        return (String) getNamedWhereClauseParam("u_name");
    }

    /**
     * Sets <code>value</code> for bind variable u_name.
     * @param value value to bind as u_name
     */
    public void setu_name(String value) {
        setNamedWhereClauseParam("u_name", value);
    }
}

