package ua.divas.view;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;

import ua.divas.model.KassaImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 17 17:24:59 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KassaViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_KASSA = 0;

    @Override
     public boolean isAttributeUpdateable(int i) {
        BigDecimal editable = this.getKEditable();
        if (editable.intValue()==0) {
            return false;
        } else {
        return super.isAttributeUpdateable(i);
            }
    }

    @Override
    protected void create(AttributeList attributeList) {
        this.setKEditable(new BigDecimal(1));
        super.create(attributeList);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        Fullname,
        IsGroup,
        ParentId,
        CurrId,
        DivisionId,
        FirmaId,
        Deleted,
        Version,
        Predefined,
        Nullable,
        KEditable,
        TotalSumm,
        TotalPrihod,
        TotalRashod,
        KassaView,
        OrdersView,
        UserSettingsView,
        OrderZamerView,
        VwKassaMoves,
        OtherZatratyView,
        KassaSettingsView,
        OrdersTpOplatyView,
        CurrencyView1,
        DivisionsView1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int FULLNAME = AttributesEnum.Fullname.index();
    public static final int ISGROUP = AttributesEnum.IsGroup.index();
    public static final int PARENTID = AttributesEnum.ParentId.index();
    public static final int CURRID = AttributesEnum.CurrId.index();
    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int FIRMAID = AttributesEnum.FirmaId.index();
    public static final int DELETED = AttributesEnum.Deleted.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int PREDEFINED = AttributesEnum.Predefined.index();
    public static final int NULLABLE = AttributesEnum.Nullable.index();
    public static final int KEDITABLE = AttributesEnum.KEditable.index();
    public static final int TOTALSUMM = AttributesEnum.TotalSumm.index();
    public static final int TOTALPRIHOD = AttributesEnum.TotalPrihod.index();
    public static final int TOTALRASHOD = AttributesEnum.TotalRashod.index();
    public static final int KASSAVIEW = AttributesEnum.KassaView.index();
    public static final int ORDERSVIEW = AttributesEnum.OrdersView.index();
    public static final int USERSETTINGSVIEW = AttributesEnum.UserSettingsView.index();
    public static final int ORDERZAMERVIEW = AttributesEnum.OrderZamerView.index();
    public static final int VWKASSAMOVES = AttributesEnum.VwKassaMoves.index();
    public static final int OTHERZATRATYVIEW = AttributesEnum.OtherZatratyView.index();
    public static final int KASSASETTINGSVIEW = AttributesEnum.KassaSettingsView.index();
    public static final int ORDERSTPOPLATYVIEW = AttributesEnum.OrdersTpOplatyView.index();
    public static final int CURRENCYVIEW1 = AttributesEnum.CurrencyView1.index();
    public static final int DIVISIONSVIEW1 = AttributesEnum.DivisionsView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public KassaViewRowImpl() {
    }

    /**
     * Gets Kassa entity object.
     * @return the Kassa
     */
    public KassaImpl getKassa() {
        return (KassaImpl) getEntity(ENTITY_KASSA);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for FULLNAME using the alias name Fullname.
     * @return the FULLNAME
     */
    public String getFullname() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FULLNAME using the alias name Fullname.
     * @param value value to set the FULLNAME
     */
    public void setFullname(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for IS_GROUP using the alias name IsGroup.
     * @return the IS_GROUP
     */
    public Integer getIsGroup() {
        return (Integer) getAttributeInternal(ISGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_GROUP using the alias name IsGroup.
     * @param value value to set the IS_GROUP
     */
    public void setIsGroup(Integer value) {
        setAttributeInternal(ISGROUP, value);
    }

    /**
     * Gets the attribute value for PARENT_ID using the alias name ParentId.
     * @return the PARENT_ID
     */
    public String getParentId() {
        return (String) getAttributeInternal(PARENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_ID using the alias name ParentId.
     * @param value value to set the PARENT_ID
     */
    public void setParentId(String value) {
        setAttributeInternal(PARENTID, value);
    }

    /**
     * Gets the attribute value for CURR_ID using the alias name CurrId.
     * @return the CURR_ID
     */
    public String getCurrId() {
        return (String) getAttributeInternal(CURRID);
    }

    /**
     * Sets <code>value</code> as attribute value for CURR_ID using the alias name CurrId.
     * @param value value to set the CURR_ID
     */
    public void setCurrId(String value) {
        setAttributeInternal(CURRID, value);
    }

    /**
     * Gets the attribute value for DIVISION_ID using the alias name DivisionId.
     * @return the DIVISION_ID
     */
    public String getDivisionId() {
        return (String) getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_ID using the alias name DivisionId.
     * @param value value to set the DIVISION_ID
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for FIRMA_ID using the alias name FirmaId.
     * @return the FIRMA_ID
     */
    public String getFirmaId() {
        return (String) getAttributeInternal(FIRMAID);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRMA_ID using the alias name FirmaId.
     * @param value value to set the FIRMA_ID
     */
    public void setFirmaId(String value) {
        setAttributeInternal(FIRMAID, value);
    }

    /**
     * Gets the attribute value for DELETED using the alias name Deleted.
     * @return the DELETED
     */
    public Integer getDeleted() {
        return (Integer) getAttributeInternal(DELETED);
    }

    /**
     * Sets <code>value</code> as attribute value for DELETED using the alias name Deleted.
     * @param value value to set the DELETED
     */
    public void setDeleted(Integer value) {
        setAttributeInternal(DELETED, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public Timestamp getVersion() {
        return (Timestamp) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(Timestamp value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for PREDEFINED using the alias name Predefined.
     * @return the PREDEFINED
     */
    public Integer getPredefined() {
        return (Integer) getAttributeInternal(PREDEFINED);
    }

    /**
     * Sets <code>value</code> as attribute value for PREDEFINED using the alias name Predefined.
     * @param value value to set the PREDEFINED
     */
    public void setPredefined(Integer value) {
        setAttributeInternal(PREDEFINED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Nullable.
     * @return the Nullable
     */
    public Integer getNullable() {
        return (Integer) getAttributeInternal(NULLABLE);
    }

    /**
     * Gets the attribute value for the calculated attribute KEditable.
     * @return the KEditable
     */
    public BigDecimal getKEditable() {
        return (BigDecimal) getAttributeInternal(KEDITABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KEditable.
     * @param value value to set the  KEditable
     */
    public void setKEditable(BigDecimal value) {
        setAttributeInternal(KEDITABLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalSumm.
     * @return the TotalSumm
     */
    public Number getTotalSumm() {
        return (Number) getAttributeInternal(TOTALSUMM);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalPrihod.
     * @return the TotalPrihod
     */
    public Number getTotalPrihod() {
        return (Number) getAttributeInternal(TOTALPRIHOD);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalRashod.
     * @return the TotalRashod
     */
    public Number getTotalRashod() {
        return (Number) getAttributeInternal(TOTALRASHOD);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link KassaView.
     */
    public RowIterator getKassaView() {
        return (RowIterator) getAttributeInternal(KASSAVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OrdersView.
     */
    public RowIterator getOrdersView() {
        return (RowIterator) getAttributeInternal(ORDERSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UserSettingsView.
     */
    public RowIterator getUserSettingsView() {
        return (RowIterator) getAttributeInternal(USERSETTINGSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OrderZamerView.
     */
    public RowIterator getOrderZamerView() {
        return (RowIterator) getAttributeInternal(ORDERZAMERVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VwKassaMoves.
     */
    public RowIterator getVwKassaMoves() {
        return (RowIterator) getAttributeInternal(VWKASSAMOVES);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OtherZatratyView.
     */
    public RowIterator getOtherZatratyView() {
        return (RowIterator) getAttributeInternal(OTHERZATRATYVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link KassaSettingsView.
     */
    public RowIterator getKassaSettingsView() {
        return (RowIterator) getAttributeInternal(KASSASETTINGSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OrdersTpOplatyView.
     */
    public RowIterator getOrdersTpOplatyView() {
        return (RowIterator) getAttributeInternal(ORDERSTPOPLATYVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CurrencyView1.
     */
    public RowSet getCurrencyView1() {
        return (RowSet) getAttributeInternal(CURRENCYVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DivisionsView1.
     */
    public RowSet getDivisionsView1() {
        return (RowSet) getAttributeInternal(DIVISIONSVIEW1);
    }
}

