package ua.divas.view;

import oracle.jbo.Row;
import oracle.jbo.Variable;
import oracle.jbo.common.VariableImpl;
import oracle.jbo.server.ViewObjectImpl;

import oracle.jbo.server.ViewRowSetImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 28 15:30:59 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KassaSettingsViewImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public KassaSettingsViewImpl() {
    }
    
    private ViewRowSetImpl getSettingsRowSet() {
        VariableImpl z = new VariableImpl();
        z.setName("UserKey");
        ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("UserSettingsView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo.findByViewCriteriaWithBindVars(vo.getViewCriteria("FilterSettingsByUser"), -1,
                                                               vo.QUERY_MODE_SCAN_DATABASE_TABLES, new Variable[] { z }, new Object[] {
                                                               this.getSessionUserId() });
        return rs;
    }

    public String retrieveCurrencyId() {
        ViewRowSetImpl rs = this.getSettingsRowSet();
        Row row = rs.first();
        if (row != null) {
            String rv = (String) row.getAttribute("CurrencyId");
            return rv;
        }
        return null;
    }


    /**
     * Returns the variable value for user_id.
     * @return variable value for user_id
     */
    public String getuser_id() {
        return (String) ensureVariableManager().getVariableValue("user_id");
    }

    /**
     * Sets <code>value</code> for variable user_id.
     * @param value value to bind as user_id
     */
    public void setuser_id(String value) {
        ensureVariableManager().setVariableValue("user_id", value);
    }

    /**
     * Returns the variable value for Curr.
     * @return variable value for Curr
     */
    public String getCurr() {
        return (String) ensureVariableManager().getVariableValue("Curr");
    }

    /**
     * Sets <code>value</code> for variable Curr.
     * @param value value to bind as Curr
     */
    public void setCurr(String value) {
        ensureVariableManager().setVariableValue("Curr", value);
    }


}

