package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 31 23:02:39 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KontragentsAllImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public KontragentsAllImpl() {
    }

    /**
     * Returns the variable value for KonId.
     * @return variable value for KonId
     */
    public String getKonId() {
        return (String) ensureVariableManager().getVariableValue("KonId");
    }

    /**
     * Sets <code>value</code> for variable KonId.
     * @param value value to bind as KonId
     */
    public void setKonId(String value) {
        ensureVariableManager().setVariableValue("KonId", value);
    }
}

