package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 12 21:04:23 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LastPriceVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LastPriceVOImpl() {
    }

    /**
     * Returns the variable value for nomenklatura.
     * @return variable value for nomenklatura
     */
    public String getnomenklatura() {
        return (String) ensureVariableManager().getVariableValue("nomenklatura");
    }

    /**
     * Sets <code>value</code> for variable nomenklatura.
     * @param value value to bind as nomenklatura
     */
    public void setnomenklatura(String value) {
        ensureVariableManager().setVariableValue("nomenklatura", value);
    }
}

