package ua.divas.view;

import oracle.jbo.Row;
import oracle.jbo.Variable;
import oracle.jbo.common.VariableImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 10 23:11:30 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NomenklaturaUslGroupImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NomenklaturaUslGroupImpl() {
    }
    
    private ViewRowSetImpl getSettingsRowSet() {
        VariableImpl z = new VariableImpl();
        z.setName("fname");
        ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("NomenklaturaView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo.findByViewCriteriaWithBindVars(vo.getViewCriteria("FilterNomByName"), -1,
                                                               vo.QUERY_MODE_SCAN_DATABASE_TABLES, new Variable[] { z }, new Object[] {
                                                               "Услуги" });
        return rs;
    }

    /**
     * Returns the bind variable value for Variable.
     * @return bind variable value for Variable
     */
    public String getprntid() {
        ViewRowSetImpl rs = this.getSettingsRowSet();
        Row row = rs.first();
        if (row != null) {
            String rv = (String) row.getAttribute("Id");
            return rv;
        }
        return (String) getNamedWhereClauseParam("prntid");
    }

    /**
     * Sets <code>value</code> for bind variable Variable.
     * @param value value to bind as Variable
     */
    public void setprntid(String value) {
        setNamedWhereClauseParam("prntid", value);
    }
}

