package ua.divas.view;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 23:14:00 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ObjectDeletedRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TableId,
        MainId,
        TableName,
        Objname,
        ConstraintType,
        RefStr,
        Mark,
        Enabled_del,
        MarkForDelete,
        Cnt,
        ObjectDeletedRef;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TABLEID = AttributesEnum.TableId.index();
    public static final int MAINID = AttributesEnum.MainId.index();
    public static final int TABLENAME = AttributesEnum.TableName.index();
    public static final int OBJNAME = AttributesEnum.Objname.index();
    public static final int CONSTRAINTTYPE = AttributesEnum.ConstraintType.index();
    public static final int REFSTR = AttributesEnum.RefStr.index();
    public static final int MARK = AttributesEnum.Mark.index();
    public static final int ENABLED_DEL = AttributesEnum.Enabled_del.index();
    public static final int MARKFORDELETE = AttributesEnum.MarkForDelete.index();
    public static final int CNT = AttributesEnum.Cnt.index();
    public static final int OBJECTDELETEDREF = AttributesEnum.ObjectDeletedRef.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ObjectDeletedRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute TableId.
     * @return the TableId
     */
    public String getTableId() {
        return (String) getAttributeInternal(TABLEID);
    }

    /**
     * Gets the attribute value for the calculated attribute MainId.
     * @return the MainId
     */
    public String getMainId() {
        return (String) getAttributeInternal(MAINID);
    }

    /**
     * Gets the attribute value for the calculated attribute TableName.
     * @return the TableName
     */
    public String getTableName() {
        return (String) getAttributeInternal(TABLENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute Objname.
     * @return the Objname
     */
    public String getObjname() {
        return (String) getAttributeInternal(OBJNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ConstraintType.
     * @return the ConstraintType
     */
    public String getConstraintType() {
        return (String) getAttributeInternal(CONSTRAINTTYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute RefStr.
     * @return the RefStr
     */
    public String getRefStr() {
        return (String) getAttributeInternal(REFSTR);
    }

    /**
     * Gets the attribute value for the calculated attribute Mark.
     * @return the Mark
     */
    public Integer getMark() {
        return (Integer) getAttributeInternal(MARK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Mark.
     * @param value value to set the  Mark
     */
    public void setMark(Integer value) {
        setAttributeInternal(MARK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Enabled_del.
     * @return the Enabled_del
     */
    public Integer getEnabled_del() {
        return (Integer) getAttributeInternal(ENABLED_DEL);
    }

    /**
     * Gets the attribute value for the calculated attribute MarkForDelete.
     * @return the MarkForDelete
     */
    public Boolean getMarkForDelete() {
        Integer mrk = this.getMark();
        if (mrk == 0) {
            return false;
        } else {
            return true;
        }
        //return (Boolean) getAttributeInternal(MARKFORDELETE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MarkForDelete.
     * @param value value to set the  MarkForDelete
     */
    public void setMarkForDelete(Boolean value) {
        if (value == true) {
            this.setMark(1);
        } else {
            this.setMark(0);
        }
        //setAttributeInternal(MARKFORDELETE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Cnt.
     * @return the Cnt
     */
    public Integer getCnt() {
        return (Integer) getAttributeInternal(CNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Cnt.
     * @param value value to set the  Cnt
     */
    public void setCnt(Integer value) {
        setAttributeInternal(CNT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ObjectDeletedRef.
     */
    public RowIterator getObjectDeletedRef() {
        return (RowIterator) getAttributeInternal(OBJECTDELETEDREF);
    }
}

