package ua.divas.view;

import oracle.jbo.Row;
import oracle.jbo.Variable;
import oracle.jbo.common.VariableImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 17 19:28:16 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderZamerViewImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public OrderZamerViewImpl() {
    }

    /**
     * Returns the bind variable value for name1.
     * @return bind variable value for name1
     */
    public String getname1() {
        ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("OrderStatusView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo
            .findByViewCriteria(vo.getViewCriteria("FilterOrderStatusByNew"), -1, vo.QUERY_MODE_SCAN_DATABASE_TABLES);
        Row row = rs.first();
        if (row != null) {
            String rv = (String) row.getAttribute("Id");
            return rv;
        }
        return (String) getNamedWhereClauseParam("name1");
    }

    /**
     * Sets <code>value</code> for bind variable name1.
     * @param value value to bind as name1
     */
    public void setname1(String value) {
        setNamedWhereClauseParam("name1", value);
    }

    /**
     * Returns the bind variable value for name2.
     * @return bind variable value for name2
     */
    public String getname2() {
        ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("OrderStatusView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo
            .findByViewCriteria(vo.getViewCriteria("FilterOrderStatusByZamer"), -1, vo.QUERY_MODE_SCAN_DATABASE_TABLES);
        Row row = rs.first();
        if (row != null) {
            String rv = (String) row.getAttribute("Id");
            return rv;
        }
        return (String) getNamedWhereClauseParam("name2");
    }

    /**
     * Sets <code>value</code> for bind variable name2.
     * @param value value to bind as name2
     */
    public void setname2(String value) {
        setNamedWhereClauseParam("name2", value);
    }

    /**
     * Returns the bind variable value for name3.
     * @return bind variable value for name3
     */
    public String getname3() {
        ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("OrderStatusView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo
            .findByViewCriteria(vo.getViewCriteria("FilterOrderStatusNotPay"), -1, vo.QUERY_MODE_SCAN_DATABASE_TABLES);
        Row row = rs.first();
        if (row != null) {
            String rv = (String) row.getAttribute("Id");
            return rv;
        }
        return (String) getNamedWhereClauseParam("name3");
    }

    /**
     * Sets <code>value</code> for bind variable name3.
     * @param value value to bind as name3
     */
    public void setname3(String value) {
        setNamedWhereClauseParam("name3", value);
    }

    /**
     * Returns the bind variable value for name4.
     * @return bind variable value for name4
     */
    public String getname4() {
        ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("OrderStatusView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo
            .findByViewCriteria(vo.getViewCriteria("FilterOrderStatusControl"), -1, vo.QUERY_MODE_SCAN_DATABASE_TABLES);
        Row row = rs.first();
        if (row != null) {
            String rv = (String) row.getAttribute("Id");
            return rv;
        }
        return (String) getNamedWhereClauseParam("name4");
    }

    /**
     * Sets <code>value</code> for bind variable name4.
     * @param value value to bind as name4
     */
    public void setname4(String value) {
        setNamedWhereClauseParam("name4", value);
    }

    /**
     * Returns the bind variable value for name5.
     * @return bind variable value for name5
     */
    public String getname5() {
        ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("OrderStatusView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo
            .findByViewCriteria(vo.getViewCriteria("FilterOrderStatusCancel"), -1, vo.QUERY_MODE_SCAN_DATABASE_TABLES);
        Row row = rs.first();
        if (row != null) {
            String rv = (String) row.getAttribute("Id");
            return rv;
        }
        return (String) getNamedWhereClauseParam("name5");
    }

    /**
     * Sets <code>value</code> for bind variable name5.
     * @param value value to bind as name5
     */
    public void setname5(String value) {
        setNamedWhereClauseParam("name5", value);
    }

    /**
     * Returns the variable value for kname.
     * @return variable value for kname
     */
    public String getkname() {
        return (String) ensureVariableManager().getVariableValue("kname");
    }

    /**
     * Sets <code>value</code> for variable kname.
     * @param value value to bind as kname
     */
    public void setkname(String value) {
        ensureVariableManager().setVariableValue("kname", value);
    }

    /**
     * Returns the bind variable value for u_name.
     * @return bind variable value for u_name
     */
    public String getu_name() {
        return (String) getNamedWhereClauseParam("u_name");
    }

    /**
     * Sets <code>value</code> for bind variable u_name.
     * @param value value to bind as u_name
     */
    public void setu_name(String value) {
        setNamedWhereClauseParam("u_name", value);
    }
}

