package ua.divas.view;

import oracle.jbo.Variable;
import oracle.jbo.common.VariableImpl;
import oracle.jbo.server.ViewObjectImpl;

import oracle.jbo.server.ViewRowSetImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 20 22:57:19 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaySettingsViewImpl extends DivasView {
    
    public String getBaseIdFix() {
        return (String) callStoredFunction(VARCHAR2, "UTILITY.retrieve_idfix_baseofcalc", new Object[] {});
    }
    
    /**
     * This is the default constructor (do not remove).
     */
    public PaySettingsViewImpl() {
    }

    /**
     * Returns the variable value for pId.
     * @return variable value for pId
     */
    public String getpId() {
        return (String) ensureVariableManager().getVariableValue("pId");
    }

    /**
     * Sets <code>value</code> for variable pId.
     * @param value value to bind as pId
     */
    public void setpId(String value) {
        ensureVariableManager().setVariableValue("pId", value);
    }

    /**
     * Returns the variable value for bId.
     * @return variable value for bId
     */
    public String getbId() {
        return (String) ensureVariableManager().getVariableValue("bId");
    }

    /**
     * Sets <code>value</code> for variable bId.
     * @param value value to bind as bId
     */
    public void setbId(String value) {
        ensureVariableManager().setVariableValue("bId", value);
    }
}

