package ua.divas.view;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.Variable;
import oracle.jbo.common.VariableImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;

import ua.divas.view.common.ProfitDistribTpView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 19 17:32:49 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProfitDistribTpViewImpl extends ViewObjectImpl implements ProfitDistribTpView {
    /**
     * This is the default constructor (do not remove).
     */
    public ProfitDistribTpViewImpl() {
    }
    
    private ViewRowSetImpl getSettingsRowSet(String pId) {
        VariableImpl z = new VariableImpl();
        z.setName("pId");
        ViewObjectImpl vo = (ViewObjectImpl) this.getRootApplicationModule().findViewObject("PaySettingsView1");
        ViewRowSetImpl rs =
            (ViewRowSetImpl) vo.findByViewCriteriaWithBindVars(vo.getViewCriteria("FindById"), -1,
                                                               vo.QUERY_MODE_SCAN_DATABASE_TABLES, new Variable[] { z }, new Object[] {
                                                               pId });
        return rs;
    }
    
    public String retrieveCalcId(String pId) {
        ViewRowSetImpl rs = this.getSettingsRowSet(pId);
        Row row = rs.first();
        if (row != null) {
            String cid = (String) row.getAttribute("BaseId");
            return cid;
        }
        return null;
    }
    
    public BigDecimal retrieveStavka(String pId) {
        ViewRowSetImpl rs = this.getSettingsRowSet(pId);
        Row row = rs.first();
        if (row != null) {
            BigDecimal stv = (BigDecimal) row.getAttribute("Stavka");
            return stv;
        }
        return null;
    }
    
    public BigDecimal retrieveSumma(String pId) {
        ViewRowSetImpl rs = this.getSettingsRowSet(pId);
        Row row = rs.first();
        if (row != null) {
            BigDecimal stv = (BigDecimal) row.getAttribute("Summa");
            return stv;
        }
        return null;
    }
}

