package ua.divas.view;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;

import ua.divas.model.RatingSettingsImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 06 20:49:01 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RatingSettingsViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_RATINGSETTINGS = 0;
    
    @Override
    public boolean isAttributeUpdateable(int i) {
        BigDecimal editable = this.getEditable();
        if (editable.intValue()==0) {
            return false;
        } else { 
        return super.isAttributeUpdateable(i);
            }
    }

    @Override
    protected void create(AttributeList attributeList) {
        this.setEditable(new BigDecimal(1));
        //this.setForValidation(new Integer(2));
        super.create(attributeList);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        SumDivider,
        SumBal,
        CntDivider,
        CntBal,
        Editable;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int SUMDIVIDER = AttributesEnum.SumDivider.index();
    public static final int SUMBAL = AttributesEnum.SumBal.index();
    public static final int CNTDIVIDER = AttributesEnum.CntDivider.index();
    public static final int CNTBAL = AttributesEnum.CntBal.index();
    public static final int EDITABLE = AttributesEnum.Editable.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RatingSettingsViewRowImpl() {
    }

    /**
     * Gets RatingSettings entity object.
     * @return the RatingSettings
     */
    public RatingSettingsImpl getRatingSettings() {
        return (RatingSettingsImpl) getEntity(ENTITY_RATINGSETTINGS);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for SUM_DIVIDER using the alias name SumDivider.
     * @return the SUM_DIVIDER
     */
    public Long getSumDivider() {
        return (Long) getAttributeInternal(SUMDIVIDER);
    }

    /**
     * Sets <code>value</code> as attribute value for SUM_DIVIDER using the alias name SumDivider.
     * @param value value to set the SUM_DIVIDER
     */
    public void setSumDivider(Long value) {
        setAttributeInternal(SUMDIVIDER, value);
    }

    /**
     * Gets the attribute value for SUM_BAL using the alias name SumBal.
     * @return the SUM_BAL
     */
    public BigDecimal getSumBal() {
        return (BigDecimal) getAttributeInternal(SUMBAL);
    }

    /**
     * Sets <code>value</code> as attribute value for SUM_BAL using the alias name SumBal.
     * @param value value to set the SUM_BAL
     */
    public void setSumBal(BigDecimal value) {
        setAttributeInternal(SUMBAL, value);
    }

    /**
     * Gets the attribute value for CNT_DIVIDER using the alias name CntDivider.
     * @return the CNT_DIVIDER
     */
    public Long getCntDivider() {
        return (Long) getAttributeInternal(CNTDIVIDER);
    }

    /**
     * Sets <code>value</code> as attribute value for CNT_DIVIDER using the alias name CntDivider.
     * @param value value to set the CNT_DIVIDER
     */
    public void setCntDivider(Long value) {
        setAttributeInternal(CNTDIVIDER, value);
    }

    /**
     * Gets the attribute value for CNT_BAL using the alias name CntBal.
     * @return the CNT_BAL
     */
    public BigDecimal getCntBal() {
        return (BigDecimal) getAttributeInternal(CNTBAL);
    }

    /**
     * Sets <code>value</code> as attribute value for CNT_BAL using the alias name CntBal.
     * @param value value to set the CNT_BAL
     */
    public void setCntBal(BigDecimal value) {
        setAttributeInternal(CNTBAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Editable.
     * @return the Editable
     */
    public BigDecimal getEditable() {
        return (BigDecimal) getAttributeInternal(EDITABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Editable.
     * @param value value to set the  Editable
     */
    public void setEditable(BigDecimal value) {
        setAttributeInternal(EDITABLE, value);
    }
}

