package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 17 23:48:22 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserSettingsViewImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public UserSettingsViewImpl() {
    }

    /**
     * Returns the variable value for UserKey.
     * @return variable value for UserKey
     */
    public String getUserKey() {
        return (String) ensureVariableManager().getVariableValue("UserKey");
    }

    /**
     * Sets <code>value</code> for variable UserKey.
     * @param value value to bind as UserKey
     */
    public void setUserKey(String value) {
        ensureVariableManager().setVariableValue("UserKey", value);
    }
}

