package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 24 20:33:26 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwKontragAllItemsImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public VwKontragAllItemsImpl() {
    }
    
    public String getBallans(String id, String code) {
        return (String)callStoredFunction(VARCHAR2,"UTILITY.ballans_by_kontr(?,?)", new Object[] {id, code});
    }
    
    /**
     * Returns the bind variable value for u_name.
     * @return bind variable value for u_name
     */
    public String getu_name() {
        return (String) getNamedWhereClauseParam("u_name");
    }

    /**
     * Sets <code>value</code> for bind variable u_name.
     * @param value value to bind as u_name
     */
    public void setu_name(String value) {
        setNamedWhereClauseParam("u_name", value);
    }

    /**
     * Returns the variable value for KonName.
     * @return variable value for KonName
     */
    public String getKonName() {
        return (String) ensureVariableManager().getVariableValue("KonName");
    }

    /**
     * Sets <code>value</code> for variable KonName.
     * @param value value to bind as KonName
     */
    public void setKonName(String value) {
        ensureVariableManager().setVariableValue("KonName", value);
    }
}

