package ua.divas.model;

import java.sql.Timestamp;

import java.util.UUID;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;

import ua.divas.classes.DivasEntityNoDelete;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 20 14:22:48 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntrySettingsImpl extends DivasEntityNoDelete {
    @Override
    protected void callId() {
        this.setId(UUID.randomUUID().toString());
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        TypedefId,
        PlanAccDebId,
        PlanAccKredId,
        Version,
        Chain,
        Description,
        PlanAcc,
        PlanAcc1,
        TypeDef;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int TYPEDEFID = AttributesEnum.TypedefId.index();
    public static final int PLANACCDEBID = AttributesEnum.PlanAccDebId.index();
    public static final int PLANACCKREDID = AttributesEnum.PlanAccKredId.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int CHAIN = AttributesEnum.Chain.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int PLANACC = AttributesEnum.PlanAcc.index();
    public static final int PLANACC1 = AttributesEnum.PlanAcc1.index();
    public static final int TYPEDEF = AttributesEnum.TypeDef.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EntrySettingsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("ua.divas.model.EntrySettings");
    }


    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for TypedefId, using the alias name TypedefId.
     * @return the value of TypedefId
     */
    public String getTypedefId() {
        return (String) getAttributeInternal(TYPEDEFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TypedefId.
     * @param value value to set the TypedefId
     */
    public void setTypedefId(String value) {
        setAttributeInternal(TYPEDEFID, value);
    }

    /**
     * Gets the attribute value for PlanAccDebId, using the alias name PlanAccDebId.
     * @return the value of PlanAccDebId
     */
    public String getPlanAccDebId() {
        return (String) getAttributeInternal(PLANACCDEBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanAccDebId.
     * @param value value to set the PlanAccDebId
     */
    public void setPlanAccDebId(String value) {
        setAttributeInternal(PLANACCDEBID, value);
    }

    /**
     * Gets the attribute value for PlanAccKredId, using the alias name PlanAccKredId.
     * @return the value of PlanAccKredId
     */
    public String getPlanAccKredId() {
        return (String) getAttributeInternal(PLANACCKREDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanAccKredId.
     * @param value value to set the PlanAccKredId
     */
    public void setPlanAccKredId(String value) {
        setAttributeInternal(PLANACCKREDID, value);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the value of Version
     */
    public Timestamp getVersion() {
        return (Timestamp) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Version.
     * @param value value to set the Version
     */
    public void setVersion(Timestamp value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for Chain, using the alias name Chain.
     * @return the value of Chain
     */
    public Long getChain() {
        return (Long) getAttributeInternal(CHAIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Chain.
     * @param value value to set the Chain
     */
    public void setChain(Long value) {
        setAttributeInternal(CHAIN, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getPlanAcc() {
        return (EntityImpl) getAttributeInternal(PLANACC);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setPlanAcc(EntityImpl value) {
        setAttributeInternal(PLANACC, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getPlanAcc1() {
        return (EntityImpl) getAttributeInternal(PLANACC1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setPlanAcc1(EntityImpl value) {
        setAttributeInternal(PLANACC1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTypeDef() {
        return (EntityImpl) getAttributeInternal(TYPEDEF);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTypeDef(EntityImpl value) {
        setAttributeInternal(TYPEDEF, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String id) {
        return new Key(new Object[] { id });
    }


}

