package ua.divas.model;

import java.sql.Timestamp;

import java.util.UUID;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;

import ua.divas.classes.DivasEntityNoDelete;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 01 13:08:33 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProgSettingsImpl extends DivasEntityNoDelete {
    
    @Override
    protected void callId() {
        this.setId(UUID.randomUUID().toString());
    }
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        DateAfter,
        DateAfterProfit;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ID = AttributesEnum.Id.index();
    public static final int DATEAFTER = AttributesEnum.DateAfter.index();
    public static final int DATEAFTERPROFIT = AttributesEnum.DateAfterProfit.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProgSettingsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("ua.divas.model.ProgSettings");
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for DateAfter, using the alias name DateAfter.
     * @return the value of DateAfter
     */
    public Timestamp getDateAfter() {
        return (Timestamp) getAttributeInternal(DATEAFTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for DateAfter.
     * @param value value to set the DateAfter
     */
    public void setDateAfter(Timestamp value) {
        setAttributeInternal(DATEAFTER, value);
    }

    /**
     * Gets the attribute value for DateAfterProfit, using the alias name DateAfterProfit.
     * @return the value of DateAfterProfit
     */
    public Timestamp getDateAfterProfit() {
        return (Timestamp) getAttributeInternal(DATEAFTERPROFIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DateAfterProfit.
     * @param value value to set the DateAfterProfit
     */
    public void setDateAfterProfit(Timestamp value) {
        setAttributeInternal(DATEAFTERPROFIT, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String id) {
        return new Key(new Object[] { id });
    }

}

