package ua.divas.view.client;

import java.util.List;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;

import ua.divas.classes.IndexCharacterObject;
import ua.divas.view.common.KontragentsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 24 20:32:12 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KontragentsViewClient extends ViewUsageImpl implements KontragentsView {
    /**
     * This is the default constructor (do not remove).
     */
    public KontragentsViewClient() {
    }


    public void createKontrag(String p_name, int isSupp, int isMeasr, int isByer) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "createKontrag", new String[] {
                                                                         "java.lang.String", "int", "int", "int"
        }, new Object[] { p_name, new Integer(isSupp), new Integer(isMeasr), new Integer(isByer) });
        return;
    }

    public void findKontragentById(String Id) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "findKontragentById", new String[] {
                                                                         "java.lang.String" }, new Object[] { Id });
        return;
    }

    public List<IndexCharacterObject> getCharacterIndexList() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getCharacterIndexList", null, null);
        return (List<IndexCharacterObject>) _ret;
    }

    public String getRowStatus(Row row) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getRowStatus", new String[] {
                                                                         "oracle.jbo.Row" }, new Object[] { row });
        return (String) _ret;
    }

    public void removeAllViewCriteria() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "removeAllViewCriteria", null, null);
        return;
    }

    public String retrieveCustomersFirstParentId() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this, "retrieveCustomersFirstParentId", null, null);
        return (String) _ret;
    }

    public String retrieveOtherParentId() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "retrieveOtherParentId", null, null);
        return (String) _ret;
    }

    public String retrieveSupplierFirstParentId() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this, "retrieveSupplierFirstParentId", null, null);
        return (String) _ret;
    }

    public String retrieveZamerFirstParentId() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this, "retrieveZamerFirstParentId", null, null);
        return (String) _ret;
    }
}

