package ua.divas.view.client;

import java.math.BigDecimal;

import oracle.jbo.client.remote.ViewUsageImpl;

import ua.divas.view.common.NachislSettingsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 20 23:14:17 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NachislSettingsViewClient extends ViewUsageImpl implements NachislSettingsView {
    /**
     * This is the default constructor (do not remove).
     */
    public NachislSettingsViewClient() {
    }

    public BigDecimal retrieveSumm(String pId) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "retrieveSumm", new String[] {
                                                                         "java.lang.String" }, new Object[] { pId });
        return (BigDecimal) _ret;
    }
}

