package ua.divas.view.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import ua.divas.view.common.ObjectDeleted;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 19:43:11 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ObjectDeletedClient extends ViewUsageImpl implements ObjectDeleted {
    /**
     * This is the default constructor (do not remove).
     */
    public ObjectDeletedClient() {
    }

    public void deleteSelectedRowsObj() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "deleteSelectedRowsObj", null, null);
        return;
    }
}

