package ua.divas.view.client;

import java.math.BigDecimal;

import oracle.jbo.client.remote.ViewUsageImpl;

import ua.divas.view.common.OrdersTpNachisleniaView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 22 17:21:48 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrdersTpNachisleniaViewClient extends ViewUsageImpl implements OrdersTpNachisleniaView {
    /**
     * This is the default constructor (do not remove).
     */
    public OrdersTpNachisleniaViewClient() {
    }

    public String retrieveCalcId(String pId) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "retrieveCalcId", new String[] {
                                                                         "java.lang.String" }, new Object[] { pId });
        return (String) _ret;
    }

    public BigDecimal retrieveStavka(String pId) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "retrieveStavka", new String[] {
                                                                         "java.lang.String" }, new Object[] { pId });
        return (BigDecimal) _ret;
    }

    public BigDecimal retrieveSumma(String pId) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "retrieveSumma", new String[] {
                                                                         "java.lang.String" }, new Object[] { pId });
        return (BigDecimal) _ret;
    }
}

