package ua.divas.view.client;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;

import ua.divas.view.common.VwKontragZamer;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 13 16:48:48 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwKontragZamerClient extends ViewUsageImpl implements VwKontragZamer {
    /**
     * This is the default constructor (do not remove).
     */
    public VwKontragZamerClient() {
    }

    public void paySelectedRows(String kassaId) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "paySelectedRows", new String[] {
                                                                         "java.lang.String" }, new Object[] {
                                                                         kassaId });
        return;
    }

    public void paySelRow(Row rw, String kassaId, BigDecimal Summ) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "paySelRow", new String[] {
                                                                         "oracle.jbo.Row", "java.lang.String",
                                                                         "java.math.BigDecimal"
        }, new Object[] { rw, kassaId, Summ });
        return;
    }

    public void paySelectedRows(String kassaId, BigDecimal Summ) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "paySelectedRows", new String[] {
                                                                         "java.lang.String", "java.math.BigDecimal"
        }, new Object[] { kassaId, Summ });
        return;
    }
}

