package ua.divas.view.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import ua.divas.view.common.ZatratyView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 26 13:54:25 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ZatratyViewClient extends ViewUsageImpl implements ZatratyView {
    /**
     * This is the default constructor (do not remove).
     */
    public ZatratyViewClient() {
    }

    public void createZatraty(String p_name) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "createZatraty", new String[] {
                                                                         "java.lang.String" }, new Object[] { p_name });
        return;
    }
}

