package ua.divas.view.ro.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 17 13:19:12 EEST 2014
// ---------------------------------------------------------------------
public interface UsersItemsLookupVO extends ViewObject {
    void setStartCriteria(String value);
}

