package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 12 20:46:32 EEST 2014
// ---------------------------------------------------------------------
public interface CompaignsView extends ViewObject {
    void addKonragentToCallList(String KonId, String CompId);

    void removeKonragentFromCallList(String KonId);
}

