package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 13 18:58:21 EEST 2014
// ---------------------------------------------------------------------
public interface CurrencyView extends ViewObject {
    void doCurrencyExchange();
}

