package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 15 19:15:33 EEST 2014
// ---------------------------------------------------------------------
public interface GroupmembersView extends ViewObject {
    void addUserToGroup(String userName, String groupName);
}

