package ua.divas.view.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 20 23:14:17 EEST 2015
// ---------------------------------------------------------------------
public interface NachislSettingsView extends ViewObject {
    BigDecimal retrieveSumm(String pId);
}

