package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 19:43:11 EEST 2015
// ---------------------------------------------------------------------
public interface ObjectDeleted extends ViewObject {
    void deleteSelectedRowsObj();
}

