package ua.divas.view.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 12 21:14:15 EET 2014
// ---------------------------------------------------------------------
public interface OrdersTpUslugiView extends ViewObject {
    String retrieveMeasure(String NomId);

    BigDecimal retrievePrice(String NomId);

    BigDecimal retrieveSumm(BigDecimal p, BigDecimal q);
}

