package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 19 00:16:13 EEST 2014
// ---------------------------------------------------------------------
public interface OrdersView extends ViewObject {
    void createContactDetail(String KonId, String Tel, String email, String Adress);

    void addEntry(String _id);

    void removeEntry(String _id);
}

