package ua.divas.view.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 19 17:34:41 EEST 2015
// ---------------------------------------------------------------------
public interface ProfitDistribTpView extends ViewObject {
    String retrieveCalcId(String pId);

    BigDecimal retrieveStavka(String pId);

    BigDecimal retrieveSumma(String pId);
}

