package ua.divas.view.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 18 13:30:18 EEST 2015
// ---------------------------------------------------------------------
public interface ProfitDistribView extends ViewObject {
    void addEntry(String _id);

    void removeEntry(String _id);

    BigDecimal getProfit();

    BigDecimal getProfitByDivision(String p_div);
}

