package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 16 20:10:34 EEST 2015
// ---------------------------------------------------------------------
public interface RkoView extends ViewObject {
    void addEntry(String _id);

    void removeEntry(String _id);

    String getOperationName(String Id);
}

