package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 02 19:37:07 EEST 2015
// ---------------------------------------------------------------------
public interface StartOstView extends ViewObject {
    void addEntry(String _id);

    void removeEntry(String _id);
}

