package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 12:41:27 EEST 2015
// ---------------------------------------------------------------------
public interface VwRating extends ViewObject {
    String retrieveKontragName(String Id);
}

