package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 05 21:58:30 EEST 2015
// ---------------------------------------------------------------------
public interface VwSupplierMoves extends ViewObject {
    void addSelectedRowsObj(String kassaId);
}

