package ua.divas.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 26 13:54:24 EEST 2015
// ---------------------------------------------------------------------
public interface ZatratyView extends ViewObject {
    void createZatraty(String p_name);
}

