package ua.divas.view.ro;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.view.ro.common.KontragentsItemsLookupVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 23 22:37:50 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KontragentsItemsLookupVOImpl extends ViewObjectImpl implements KontragentsItemsLookupVO {
    /**
     * This is the default constructor (do not remove).
     */
    public KontragentsItemsLookupVOImpl() {
    }

    /**
     * Returns the variable value for StartCriteria.
     * @return variable value for StartCriteria
     */
    public String getStartCriteria() {
        return (String) ensureVariableManager().getVariableValue("StartCriteria");
    }

    /**
     * Sets <code>value</code> for variable StartCriteria.
     * @param value value to bind as StartCriteria
     */
    public void setStartCriteria(String value) {
        ensureVariableManager().setVariableValue("StartCriteria", value);
    }
}

